version: '3.0'

services:
  main:
    entrypoint: ["sh", "./entrypoint.sh"]
    container_name: main
    build:
      context: .
    env_file:
      - .docker.env
    volumes:
      - .:/app
      - app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
#    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .docker.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
#    restart: always

  redis:
    container_name: redis
    image: redis
    env_file:
      - .docker.env
    ports:
      - 6378:6379
    volumes:
      - redisdata:/data
#    restart: always

volumes:
  pgdata:
  redisdata: